### your site title here

title: Ufuk Kayserilioglu
description: Engineering Manager | Ruby Infrastructure Team @ Shopify

baseurl: "" #name of GitHub repository
url: "ufuk.dev" #custom url to be used instead of GitHub repository
email: ufuk@paralaus.com


highlighter: rouge
markdown: kramdown

# Pagination
paginate: 15
permalink: /posts/:title/
paginate_path: /posts/page:num/

# Social media links in footer
twitter: "paracycle"
linkedin: "ufukkayserilioglu"
github: "paracycle"

# Tracker
analytics:

#optimization -> compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

#collection
collections:
  projects:
    output: true
    permalink: /projects/:path/

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages
  - assets/images

exclude:
  - README.md
  - LICENSE.md

defaults:
  - scope:
      path: "assets/images"
    values:
      image: true

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-email-protect
  - jekyll-target-blank
