baseurl: ""

title: "Ufuk Kayserilioglu"
description: "Engineering Manager - Ruby Infrastructure Team at Shopify"
url: "https://ufuk.dev"
email: ufuk@paralaus.com

# SEO
twitter:
  username: paracycle
  card: summary

social:
  name: Ufuk Kayserilioglu
  links:
    - https://twitter.com/paracycle
    - https://github.com/paracycle
    - https://linkedin.com/in/ufukkayserilioglu


highlighter: rouge
markdown: kramdown

# Pagination
paginate: 15
permalink: /posts/:title/
paginate_path: /posts/page:num/

# Social media links in footer
social:
  twitter: "paracycle"
  linkedin: "ufukkayserilioglu"
  github: "paracycle"

# Tracker
analytics:

#optimization -> compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

#collection
collections:
  projects:
    output: true
    permalink: /projects/:path/
  talks:
    output: false
    permalink: /talks/:path/
  podcasts:
    output: false
    permalink: /podcasts/:path/

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages
  - assets/images

exclude:
  - README.md
  - LICENSE.md

navigation:
  - title: Home
    url: /
  - title: Talks
    url: /talks/
  - title: Podcasts
    url: /podcasts/
  - title: Posts
    url: /posts/
  - title: Archive
    url: /archive/

defaults:
  - scope:
      path: "assets/images"
    values:
      image: true

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-email-protect
  - jekyll-target-blank
  - jekyll-compose
